### ISSUE TITLE
error on study query

### ISSUE THREAD

**Issue by dglecons** [Zaid-Safadi/DICOMcloud#5] opened 2016-08-25 12:20 UTC
question on the dicom cloud project
i get this error on study query from the demo project to cloud application
An exception of type 'System.TypeInitializationException' occurred in DICOMcloud.Wado.Core.dll but was not handled in user code
Additional information: The type initializer for 'DICOMcloud.Wado.Core.DefaultDicomQueryElements' threw an exception.

**Comment by Zaid-Safadi** [comment] 2016-08-26 03:05
The exception seems to be happening in the static constructor of the class "DefaultDicomQueryElements". 
The only thing that is happening there is initializing a template DicomDataset with empty elements, which leads me to think it is something with the Dicom toolkit.

I'll need to get some information to assist you with this:
Are you hosting your own server or using the online hosted server? 
Does the query fail on the hosted version?

Which branch of the server are you testing with, fo-dicom-integration or master?

For the fo-dicom-integration please make sure you are using the Dicom libraries in the resources "Resources/Bin" folder:
Dicom.Core.dll
Dicom.Platform.dll
Dicom.Native.dll/Dicom.Native64.dll

For the master branch, use the ClearCanvas dlls:
1. ClearCanvas.Dicom.dll
2. ClearCanvas.Common.dll

If using the above fixes your problem, please let me know the Dicom toolkit version number you are using causing the error. Otherwise, provide me with any instructions to help me reproduce.

**Comment by dglecons** [comment] 2016-08-29 17:57
with clearcanvas verison i am not getting this error.right now i am using
this to proceed.
it happens only with fodicom version.

i have not hosted so far..i was just checking and running both client and
server in my test pc.

**Comment by Zaid-Safadi** [comment] 2016-08-30 01:19
This should also work with fo-dicom dll that I have in my resources\bin folder. The version that I have is an update to fo-dicom v2.0 but < 3.0. Once v3.0 is released I'll update the project to use that.
The fo-dicom is what I'm basing bug fixes and future updates on. ClearCanvase is a reference only for such cases.

**Comment by Zaid-Safadi** [comment] 2016-09-17 01:36
@dglecons  I'm closing this ticket for now, if you still running into issues please let me know.

I also have now a new branch "development" that is updated with the latest fo-dicom v3 pre release.

**Closed as completed by Zaid-Safadi** 2016-09-17 01:36 UTC
